version: '3'

services:
  emosense-app:
    container_name: emosense-app
    image: node:18.16.0
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: bash -c "npm install --force && npx prisma generate && npm run dev"
    ports:
      - "5555:5555"
    depends_on:
      - emosense-mysql
    restart: always

  emosense-mysql:
    container_name: emosense-mysql
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
