import Head from 'next/head'
import Avatar from '@/components/Avatar';
import Writer from '@/components/Writer';
import Link from 'next/link';

export default function Home() {

    const text = "Welcome to our AI-based therapy program. We're here to help you explore your thoughts and feelings and access treatment in a supportive environment. Our program uses customized algorithms to create a treatment plan that addresses your specific needs and concerns. Our goal is to provide you with the tools you need to increase happiness and fulfillment in your life. You can rest assured that our AI therapy program is safe and confidential. If you need further assistance, our technical support is happy to help you at every step."

    return (
        <>
            <Head>
                <title>Emosense Therapy</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Writer text={text} color={"#fff"} minHeight={"80px"} />
            <Avatar />
            <Link className='custom-button' href={"/ChatAi"}>Talk</Link>
        </>
    )
}
