import Head from "next/head";
import Avatar from "@/components/Avatar";
import Writer from "@/components/Writer";
import Link from "next/link";
import avatarLotie from "@/assets/avatar"

export default function Home() {
    const text = `Welcome to our AI-based therapy program.
     We're here to help you explore your thoughts and feelings and access treatment in a supportive environment.
      Our program uses customized algorithms to create a treatment plan that addresses your specific needs and concerns.
       Our goal is to provide you with the tools you need to increase happiness and fulfillment in your life.
        You can rest assured that our AI therapy program is safe and confidential.
         If you need further assistance, our technical support is happy to help you at every step.`;

         const avatars = [
            "https://svgsilh.com/svg/1299642.svg",
            "https://svgsilh.com/svg/1299642.svg",
            "https://svgsilh.com/svg/1299642.svg"
          ];

          const handleAvatarSelect = (avatar) => {
            console.log(`Selected avatar: ${avatar}`);
          };

    return (
        <>
            <Head>
                <title>CogniTalk Ai</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
            </Head>
            <Writer text={text} color={"#fff"} minHeight={"80px"} />
            <Avatar animation={avatarLotie} width={400} height={400} />
            <Link className="custom-button" href={"/ChatAi"}>
                Talk
            </Link>
        </>
    );
}
